language: python
python:
  - "3.4"
install:
# command to install dependencies
  - "pip install -e ."
# create the config
  - "echo DEBUG=True > lint-computer.conf.py"
# command to run tests
script: "lint-computer test"